FROM ubuntu:16.04

# Install nedeed tools for TurboParser and TurboTextAnalysis
RUN apt-get update && apt-get install -y wget build-essential automake autoconf git unzip libconfig++8-dev libicu-dev python3 cython3 python3-flask